server:
  port: 80
  servlet:
    context-path: /heyanwei
mybatis:
  config-location:
  mapper-locations:
spring:
  datasource:
    url: jdbc:mysql://rm-wz9g2it2n0vggu21u.mysql.rds.aliyuncs.com:3306/heyanwei
    username: heyanwei
    password: zly761563491@0
#  rabbitmq:
#      host: localhost
#      port: 5672
#      username: guest
#      password: guest
#      publisher-confirms: true
#      publisher-returns: true
#      virtual-host: /
#      listener:
#        acknowledge-mode: manual